parameters:
  - name: "MaxSpeed"
    type: "float"
    range: [0.0, 5.0]
    unit: "m/s"
    description: "最大速度"

  - name: "OperationMode"
    type: "enum"
    values: ["AUTO", "MANUAL", "TEST"]
    description: "動作モード"

  - name: "EnableLogging"
    type: "bool"
    description: "ログ出力を有効にする"

  - name: "IPAddress"
    type: "ip"
    description: "接続先デバイスのIPアドレス"